name: CI/CD Pipeline Part 2 (Pokemon Tests)

on:
  push:
    branches: [ main ] # just a hw assignment, so there are no branches
  pull_request:
    branches: [ main ]
  workflow_dispatch: # to manually trigger :D


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Original Pokemon Tests
      run: |
        PYTHONPATH=src pytest tests/test_pokemon.py -v

    - name: Run REST API Tests
      run: |
        PYTHONPATH=src pytest tests/test_api.py -v

    - name: Build Docker Images
      run: |
        docker build -f docker/Dockerfile.api -t pokemon-api .
        docker build -f docker/Dockerfile.tests -t pokemon-api-tests .

    - name: Test Docker Test Container
      run: |
        docker run --rm pokemon-api-tests
